{"name": "Obtener perfil", "status": "failed", "statusDetails": {"message": "AssertionError: Error al consultar el perfil\n", "trace": "  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\user_profile.py\", line 56, in validate_response_get_user\n    assert context.response.status_code == 200, 'Error al consultar el perfil'\n"}, "description": "Give usuario registrado previamente con ID 1", "steps": [{"name": "When se envia una solicitud para obtener el perfil de un usuario con ID 1", "status": "passed", "start": 1715895731646, "stop": 1715895732054}, {"name": "Then se recibe una respuesta exitosa con la informacion del perfil del usuario", "status": "failed", "statusDetails": {"message": "AssertionError: Error al consultar el perfil\n", "trace": "  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\user_profile.py\", line 56, in validate_response_get_user\n    assert context.response.status_code == 200, 'Error al consultar el perfil'\n"}, "start": 1715895732054, "stop": 1715895732057}], "start": 1715895731643, "stop": 1715895732059, "uuid": "c080ebb2-aa77-486d-8a70-c4b30be94700", "historyId": "ad4cb42393d7289192ca1e33dfcb7b33", "fullName": "Gestión de Perfiles: Obtener perfil", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Gestión de Perfiles"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}