{"name": "Obtener perfil", "status": "failed", "statusDetails": {"message": "AssertionError: Error al consultar el perfil\n", "trace": "  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\user_profile.py\", line 56, in validate_response_get_user\n    assert context.response.status_code == 200, 'Error al consultar el perfil'\n"}, "description": "Give usuario registrado previamente con ID 1", "steps": [{"name": "When se envia una solicitud para obtener el perfil de un usuario con ID 1", "status": "passed", "start": 1715896666649, "stop": 1715896667741}, {"name": "Then se recibe una respuesta exitosa con la informacion del perfil del usuario", "status": "failed", "statusDetails": {"message": "AssertionError: Error al consultar el perfil\n", "trace": "  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Camilo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps\\user_profile.py\", line 56, in validate_response_get_user\n    assert context.response.status_code == 200, 'Error al consultar el perfil'\n"}, "start": 1715896667741, "stop": 1715896667748}], "start": 1715896666646, "stop": 1715896667750, "uuid": "bb088bb8-c360-4314-a4b6-49fcc898e95c", "historyId": "ad4cb42393d7289192ca1e33dfcb7b33", "fullName": "Gestión de Perfiles: Obtener perfil", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Gestión de Perfiles"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}